name: TypeScript CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: 'Install pnpm'
        run: npm i -g pnpm
      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile
      - name: 'TypeScript Type Check'
        run: pnpm run type-check
      - name: 'Lint TypeScript'
        run: pnpm run lint
      - name: 'Check Formatting'
        run: pnpm run format:check
      - name: 'Build TypeScript'
        run: pnpm run build
